export const userTypes = {
    PHONELOGIN_USER: "PHONELOGIN_USER",
    AUTHENTICATION_USER: "AUTHENTICATION_USER",
    CREATE_USER: "CREATE_USER",
    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
  };